# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Deploy and Test Game Store

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Running NPM CI
          run: npm ci
        - name: Running NPM Build
          run: npm run build
        - name: Setting AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{secrets.AWS_BUCKET_REGION}}
        - name: Sync with S3
          run: aws s3 sync dist/ ${{secrets.AWS_BUCKET}}
  python-playwright:
    uses: AbyssalWhale/python-pw/.github/workflows/reusable-workflow.yml@main
    needs: build
    with:
        check-out-path: ./py-playwright
        publish-aws: true
    secrets: 
        instance-backend-api-key: ${{secrets.RAWG_KEY}}
        aws-bucket-region: ${{secrets.AWS_BUCKET_REGION}}
        aws-bucket: ${{secrets.AWS_BUCKET}}
        aws-key: ${{secrets.AWS_KEY_ID}}
        aws-a-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
  dotnettests-playwright:
    uses: AbyssalWhale/AutomationTests-PW/.github/workflows/reusable-workflow.yml@main
    needs: build
    with:
        check-out-path: ./dotnet-playwright
        branch: develop
        zephyr-is-publishresults: false
        zephyr-cycle-name: default
        zephyr-cycle-comment: default
    secrets:
        instance-ui-url: ${{secrets.INSTANCE_URL}}
        instance-backend-url: ${{secrets.INSTANCE_BACKEND_URL}}
        instance-backend-api-key: ${{secrets.RAWG_KEY}}
        instance-backend-api-token: ${{secrets.INSTANCE_BACKEND_API_TOKEN}}
        zephyr-token: ${{secrets.ZEPHYR_TOKEN}}
        zephyr-projectKey: ${{secrets.ZEPHYR_PROJECT_KEY}}
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
