# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy and Test Game Store

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Running NPM CI
          run: npm ci
        - name: Running NPM Build
          run: npm run build
        - name: Setting AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: eu-central-1
        - name: Sync with S3
          run: aws s3 sync dist/ s3://awoha.xyz
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout Tests
      uses: actions/checkout@v2
      with:
        repository: AbyssalWhale/python-pw
        path: './python-tests'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-playwright
        pip install pytest-reporter-html1
        pip install pytest-xdist
        python -m pip install playwright
    - name: Install playwright browsers
      run: | 
        python -m playwright install
        npx playwright install-deps
    - name: Run Tests
      run: pytest './python-tests/' -m regression --report=report.html --template=html1/index.html -n auto
